logging.level.root=off
logging.level.org.testcontainers=WARN
logging.level.com.github.dockerjava=ERROR

spring.main.banner-mode=off
spring.main.web-application-type=none
spring.shell.history.enabled=false
spring.shell.interactive.enabled=true